import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read the built index.html
const indexPath = path.join(__dirname, '..', 'dist', 'index.html');
const htmlContent = fs.readFileSync(indexPath, 'utf-8');

// Escape the HTML for JavaScript string
const escapedHtml = htmlContent
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\${/g, '\\${')
  .replace(/\n/g, '\\n')
  .replace(/'/g, "\\'")
  .replace(/"/g, '\\"');

// Generate the JavaScript file content
const jsContent = `// Auto-generated file - DO NOT EDIT
// Generated by scripts/inject-assets.js during build
export const indexHtml = "${escapedHtml}";
`;

// Write to dist/worker-voice/generated-index.js
const outputPath = path.join(__dirname, '..', 'dist', 'worker-voice', 'generated-index.js');
const outputDir = path.dirname(outputPath);

// Ensure directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, jsContent, 'utf-8');
console.log('✅ Generated index.html injection file:', outputPath);

